apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tautulli-pvc-rwo
  namespace: tautulli
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: longhorn
  volumeName: pvc-9122aba2-3af4-4e91-b98a-9cc1198509a5
  resources:
    requests:
      storage: 2Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tautulli
  namespace: tautulli
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: tautulli
  template:
    metadata:
      labels:
        app: tautulli
    spec:
      containers:
      - env:
        - name: PUID
          value: "1000"
        - name: PGID
          value: "1000"
        - name: TZ
          value: America/New_York
        image: lscr.io/linuxserver/tautulli:latest
        name: tautulli
        ports:
        - containerPort: 8181
        volumeMounts:
        - mountPath: /config
          name: tautulli-config
        readinessProbe:
          httpGet:
            path: /status
            port: 8181
          initialDelaySeconds: 15
          periodSeconds: 15
        livenessProbe:
          httpGet:
            path: /status
            port: 8181
          initialDelaySeconds: 30
          periodSeconds: 20
      volumes:
      - name: tautulli-config
        persistentVolumeClaim:
          claimName: tautulli-pvc-rwo
---
apiVersion: v1
kind: Service
metadata:
  name: tautulli
  namespace: tautulli
spec:
  type: ClusterIP
  selector:
    app: tautulli
  ports:
  - port: 8181
    targetPort: 8181
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: tautulli
  namespace: tautulli
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
spec:
  ingressClassName: traefik
  rules:
  - host: tautulli.home.arpa
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: tautulli
            port:
              number: 8181
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: tautulli
  namespace: tautulli
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      app: tautulli
