apiVersion: apps/v1
kind: Deployment
metadata:
  name: plex
  namespace: plex
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: plex
  template:
    metadata:
      labels:
        app: plex
    spec:
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: gpu
                operator: In
                values:
                - rtx3060
                - teslap4
      runtimeClassName: nvidia
      containers:
      - env:
        - name: PUID
          value: "1000"
        - name: PGID
          value: "1000"
        - name: TZ
          value: America/New_York
        - name: VERSION
          value: docker
        - name: NVIDIA_VISIBLE_DEVICES
          value: all
        - name: NVIDIA_DRIVER_CAPABILITIES
          value: compute,video,utility
        image: lscr.io/linuxserver/plex:latest
        name: plex
        ports:
        - containerPort: 32400
        volumeMounts:
        - mountPath: /config
          name: plex-config
        - mountPath: /data
          name: data
        - mountPath: /transcode
          name: transcode
      volumes:
      - name: plex-config
        persistentVolumeClaim:
          claimName: plex-pvc-rwo
      - name: data
        persistentVolumeClaim:
          claimName: media-data-pvc
      - name: transcode
        emptyDir:
          medium: Memory
          sizeLimit: 4Gi
