apiVersion: v1
kind: PersistentVolume
metadata:
  name: media-data-pv-plex
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 500Gi
  nfs:
    path: /volume1/Storage/data
    server: 192.168.0.183
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media-data-pvc
  namespace: plex
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 500Gi
  storageClassName: ""
  volumeName: media-data-pv-plex
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: plex-pvc-rwo
  namespace: plex
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  volumeName: pvc-d3c6f5cf-a04d-4e86-9346-0b8c70ea425b
  resources:
    requests:
      storage: 8Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: plex
  namespace: plex
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: plex
  template:
    metadata:
      labels:
        app: plex
    spec:
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: gpu
                operator: In
                values:
                - rtx3060
                - teslap4
      runtimeClassName: nvidia
      containers:
      - env:
        - name: PUID
          value: "1000"
        - name: PGID
          value: "1000"
        - name: TZ
          value: America/New_York
        - name: VERSION
          value: docker
        - name: NVIDIA_VISIBLE_DEVICES
          value: all
        - name: NVIDIA_DRIVER_CAPABILITIES
          value: compute,video,utility
        image: lscr.io/linuxserver/plex:latest
        name: plex
        ports:
        - containerPort: 32400
        volumeMounts:
        - mountPath: /config
          name: plex-config
        - mountPath: /data
          name: data
        - mountPath: /transcode
          name: transcode
      volumes:
      - name: plex-config
        persistentVolumeClaim:
          claimName: plex-pvc-rwo
      - name: data
        persistentVolumeClaim:
          claimName: media-data-pvc
      - name: transcode
        emptyDir:
          medium: Memory
          sizeLimit: 4Gi
---
apiVersion: v1
kind: Service
metadata:
  name: plex
  namespace: plex
spec:
  type: NodePort
  selector:
    app: plex
  ports:
  - port: 32400
    targetPort: 32400
    nodePort: 32400
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: plex
  namespace: plex
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
spec:
  ingressClassName: traefik
  rules:
  - host: plex.home.arpa
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: plex
            port:
              number: 32400
