apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bark
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/thekolbstr/homelab-gitops.git
    targetRevision: main
    path: bark
  destination:
    server: https://kubernetes.default.svc
    namespace: bark
  syncPolicy:
    automated:
      prune: false
      selfHeal: true