apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nascar-schedule
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/thekolbstr/homelab-gitops.git
    targetRevision: main
    path: nascar-schedule
  destination:
    server: https://kubernetes.default.svc
    namespace: nascar-schedule
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      prune: false
      selfHeal: true
