apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: plex
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: plex=lscr.io/linuxserver/plex
    argocd-image-updater.argoproj.io/plex.update-strategy: newest-build
    argocd-image-updater.argoproj.io/plex.allow-tags: 'regexp:^[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+-[0-9a-f]+-ls[0-9]+$'
    argocd-image-updater.argoproj.io/write-back-method: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/thekolbstr/homelab-gitops.git
    targetRevision: main
    path: plex
  destination:
    server: https://kubernetes.default.svc
    namespace: plex
  syncPolicy:
    automated:
      prune: false
      selfHeal: true