apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tailscale
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/thekolbstr/homelab-gitops.git
    targetRevision: main
    path: tailscale
  destination:
    server: https://kubernetes.default.svc
    namespace: tailscale
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      prune: false
      selfHeal: true
