apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gotify-pvc-rwo
  namespace: gotify
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: longhorn
  volumeName: pvc-80fc6038-1536-4901-bd28-b73182895679
  resources:
    requests:
      storage: 2Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gotify
  namespace: gotify
  labels:
    app: gotify
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: gotify
  template:
    metadata:
      labels:
        app: gotify
    spec:
      containers:
      - env:
        - name: GOTIFY_SERVER_PORT
          value: "80"
        - name: GOTIFY_DEFAULTUSER_NAME
          value: kolby
        - name: GOTIFY_DEFAULTUSER_PASS
          value: changeme
        image: gotify/server:latest
        name: gotify
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: 200m
            memory: 256Mi
          requests:
            cpu: 50m
            memory: 64Mi
        volumeMounts:
        - mountPath: /app/data
          name: data
        readinessProbe:
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: 15
          periodSeconds: 15
        livenessProbe:
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 20
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: gotify-pvc-rwo
---
apiVersion: v1
kind: Service
metadata:
  name: gotify
  namespace: gotify
spec:
  type: NodePort
  selector:
    app: gotify
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30881
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: gotify-ingress
  namespace: gotify
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
spec:
  ingressClassName: traefik
  rules:
  - host: gotify.fullsendbud.xyz
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: gotify
            port:
              number: 80
  - host: gotify.home.arpa
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: gotify
            port:
              number: 80
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: gotify
  namespace: gotify
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      app: gotify
