apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: appdata-pvc
  namespace: media
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
  storageClassName: ""
  volumeName: appdata-pv
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bark-pvc
  namespace: media
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: local-path
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: beszel-pvc
  namespace: media
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: local-path
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gotify-pvc
  namespace: media
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: ""
  volumeName: gotify-pv
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: igotify-pvc
  namespace: media
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: ""
  volumeName: igotify-pv
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jellyfin-config-local-pvc
  namespace: media
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: local
  volumeName: jellyfin-config-local-pv
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media-data-pvc
  namespace: media
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 500Gi
  storageClassName: ""
  volumeName: media-data-pv
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: plex-config-local-pvc
  namespace: media
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  storageClassName: local
  volumeName: plex-config-local-pv
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: radarr-local-pvc
  namespace: media
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: local
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sonarr-local-pvc
  namespace: media
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: local
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tautulli-config-local-pvc
  namespace: media
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: local
  volumeName: tautulli-config-local-pv
