---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: vpn-stack-secrets
  namespace: media
spec:
  encryptedData:
    wireguard-private-key: AgCzOZYzeBZkW/i2Scyi73A/mPRaz52mpZ0vCJf+d85LhoZaY5PGTl/iH25x9zxmYhM37WOYTFXw7jIHiuRC052yp+A8TYhX/eOI7h3qkZjB5ivXyc/ebkikEvixe/S1pEtYE9KJCNybU73ihBNRT+oN/SYvSCshQu1XlnISO4VqvSe2SVBNue5P48ta6lHt5AcT5QzzkK9zq2A/IPnkIMlpJtb7lIXH9rL2clJ6hxY0pJ9Ekyk0Mb7OMjsVDzr0mY9sEK4lzHK+9OC01fyrr2ClyBxTVzoUw7zL3o96eFmo6Id4+WAKqLmu2dlvIjKbpuwtVuOskBlRiqYM/AdCNrrkW6WZlnnM7TTI3I24ZD6Y+gauF2sREwEIcaabVU/Ew8USQ3CoH62qIoZdtzMPLLRaFcPZLmvWv3wr258C+70j8FwpJE0mr6L4ABE2ioEBGib7PFNBAWHnWV+r5/r4WKtHWoiidVHBFmGbjLcEhlUDLMozWdfUYOU1OVgkCkhzvnZ1Syt2Sh/J12ORcbqxBBff8ehMWnTtED2CGHzj5CHmdhcnG7/5TXOS/UXT4YbJHSw6mqYB6gmvarO1mBGF6EFfctipbCJHyIjdwUZX2GR2vG7jKr8reyL1NjmLbdt4dxP+JrMRgmyAT7ps8vIYnGrTs5WJ5VELJQjkMn5+ml3P9jHsxQ0GnfkNytsvY0Z8KTb1576UxNci0Z+q8ahTkww2hjmO8PStn18p5/CzbzhksU3yKKRc4C/lyDl5Bw==
  template:
    metadata:
      creationTimestamp: null
      name: vpn-stack-secrets
      namespace: media
    type: Opaque
