apiVersion: v1
kind: Service
metadata:
  name: vpn-stack
  namespace: media
spec:
  type: NodePort
  selector:
    app: vpn-stack
  ports:
  - name: dispatcharr
    port: 9191
    targetPort: 9191
    nodePort: 30991
  - name: sabnzbd
    port: 8080
    targetPort: 8080
    nodePort: 30080
  - name: qbittorrent
    port: 8090
    targetPort: 8090
    nodePort: 30090
  - name: prowlarr
    port: 9696
    targetPort: 9696
    nodePort: 30696
  - name: byparr
    port: 8191
    targetPort: 8191
    nodePort: 30191
