apiVersion: v1
kind: PersistentVolume
metadata:
  name: media-data-pv-radarr
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 500Gi
  nfs:
    path: /volume1/Storage/data
    server: 192.168.0.183
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media-data-pvc
  namespace: radarr
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 500Gi
  storageClassName: ""
  volumeName: media-data-pv-radarr
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: radarr-pvc-rwo
  namespace: radarr
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: longhorn
  volumeName: radarr-vol-restored
  resources:
    requests:
      storage: 10Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: radarr
  namespace: radarr
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: radarr
  template:
    metadata:
      labels:
        app: radarr
    spec:
      containers:
      - env:
        - name: PUID
          value: "1000"
        - name: PGID
          value: "1000"
        - name: TZ
          value: America/New_York
        image: lscr.io/linuxserver/radarr:latest
        name: radarr
        ports:
        - containerPort: 7878
        volumeMounts:
        - mountPath: /config
          name: config
        - mountPath: /data
          name: data
        - mountPath: /movies
          name: data
          subPath: media/movies
        readinessProbe:
          httpGet:
            path: /ping
            port: 7878
          initialDelaySeconds: 15
          periodSeconds: 15
        livenessProbe:
          httpGet:
            path: /ping
            port: 7878
          initialDelaySeconds: 30
          periodSeconds: 20
      volumes:
      - name: config
        persistentVolumeClaim:
          claimName: radarr-pvc-rwo
      - name: data
        persistentVolumeClaim:
          claimName: media-data-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: radarr
  namespace: radarr
spec:
  type: ClusterIP
  selector:
    app: radarr
  ports:
  - name: http
    port: 7878
    targetPort: 7878
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: radarr
  namespace: radarr
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
spec:
  ingressClassName: traefik
  rules:
  - host: radarr.home.arpa
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: radarr
            port:
              number: 7878
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: radarr
  namespace: radarr
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      app: radarr
