apiVersion: v1
kind: PersistentVolume
metadata:
  name: appdata-pv-homepage
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 100Gi
  mountOptions:
  - noatime
  - nodiratime
  - rsize=131072
  - wsize=131072
  - nfsvers=4.1
  - hard
  - timeo=600
  - retrans=2
  nfs:
    path: /volume1/Storage/appdata
    server: 192.168.0.183
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: appdata-pvc
  namespace: homepage
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
  storageClassName: ""
  volumeName: appdata-pv-homepage
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: homepage
  namespace: homepage
spec:
  replicas: 1
  selector:
    matchLabels:
      app: homepage
  template:
    metadata:
      labels:
        app: homepage
    spec:
      containers:
      - env:
        - name: TZ
          value: America/New_York
        - name: HOMEPAGE_ALLOWED_HOSTS
          value: '*'
        image: ghcr.io/gethomepage/homepage:latest
        name: homepage
        ports:
        - containerPort: 3000
        volumeMounts:
        - mountPath: /app/config
          name: appdata
          subPath: homer
        readinessProbe:
          httpGet:
            path: /api/healthcheck
            port: 3000
          initialDelaySeconds: 15
          periodSeconds: 15
        livenessProbe:
          httpGet:
            path: /api/healthcheck
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 20
      volumes:
      - name: appdata
        persistentVolumeClaim:
          claimName: appdata-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: homepage
  namespace: homepage
spec:
  type: ClusterIP
  selector:
    app: homepage
  ports:
  - port: 3000
    targetPort: 3000
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: homepage
  namespace: homepage
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
spec:
  ingressClassName: traefik
  rules:
  - host: homepage.home.arpa
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: homepage
            port:
              number: 3000
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: homepage
  namespace: homepage
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      app: homepage
