---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: argocd-notifications-secret
  namespace: argocd
spec:
  encryptedData:
    bark-device-key: AgASJ9KbUvqPYCDmerPdazF44oM7JpJ/uwnRLN3Y0S2YHkv7u2NyQQD6VqzhgL6O/uhCQ4yzW3/2SKELufftIQaaKoWdA9K1jE4VpPCT71CPASeiBSzkdRk3P+BQ6U9xTb20Iri1v8vVvrGMO/KxtLiGozmKxFvOKd4IpIekQAoCRsJWCAt11mc81DOP5/RtEN2mClT9j/9Vfssy8EdQgsztwngMjfPxSG70MJUYPwq2TndhEedK7J9f3ZUwoUqbpJpBhPpr36/dTkkI3WQQifKYXBj79NoFF/cxpJ9FGrGjcHvGt0g7KYk7ePo7d/OM5iQBL4scc0Z+IQUUm9Um/TMJtK34CWZWefqKFMJhs/7UM0wDsWBFhyZUQWffIbzm4DYb2Ik7srv7KbP2xVThdOf6MxK8it0VsRq1Eui3y4IDMZ/2kj/is8Ll/EduZR37vIe9yaBji1vlZAj5AxWthbZOaWy/Cl8CrQhjdLsCqy5cq+weagPQ/bFrCytAn/grfUFBGlYzXvg9xWM8CDC9pwh1zagQGCpzf+5/Z5VeRCt8CYdsUVMSPAv+OjySl7z0vCnZWHErOjBwyWdT2bleBXJ28TT8Hx736tIYtExbX5W/I3wtGvsZTMqw29smvloxhdESYqt56NyqvF43LZ7Mx7T6j8dmGG9zxc/L9+Wt0rXpvIP7MmUeva2oOAM7uCsO1PxEGJHtSR4+C09KcXrvRrBzuiY8B49c
    gotify-token: AgBfqwWufBJ9AySVsYcRrobmFiPYm18VnkNpmu91T5nrNccZMcYhMuq2cw0n0AT3fFLQQfO8gsir7Al0K8ceZr8LhNKLb+IL+Ub9w+DpYlA/fHlyyPhdhRQwnjGdGfh8415Jo9vQx32J51RYzsSlyST+zyj4bnlP1VgtjQrUA7TUI+XIS5sZr2J1W1Icw69DI+iH+mQUlf3PXz8w4GF6sbqOwu3OjmheJy3jvu+FNGiCSVPSEwjQGslFldYMg+6xaLLltscCyjopqrO+2sw0vSQxLsXyXUfa755vDG6aDYflSZ51UmCF3lxn3dwz08OKIF1qB40sDkIe7XFo3EI49JfbuJD/kEJrX3OlTRCMz0ZwBiNWDcoYUeEI5ojk2lesPc12OiCJ8OFugmJCTJd+VZOdbhoKNafFli1vN6xv3OMPY9KjOitsXENc2r8GLo0LOjrYHQllXk1hvtxnQURFj/R64QExrpVWJ4Z7beq+K+owRu06iXRbdMeIS8wG/yRs4LgU/0AnC6D/0P1/Eu5KOR3CEiAeu4py7/32x10U5UwINzMfRctmhnwk36/cj44cUuUS/rN562TjXHuBogeAjMiarkM1UnsRR8RphKXyyrEFBeAmT23PjMq8wDi7BjZeTD/yA5o9f51HpcYkrTf0BoVKl/GXR87naqq3ct+VTHwCnfF2xX4yqpv6Au0LKgjENQWrWYhPa3l5+id//UFuza8=
  template:
    metadata:
      creationTimestamp: null
      name: argocd-notifications-secret
      namespace: argocd
    type: Opaque
